Repository CmpGameDevs/CRougeLite, pull requests merged in 2024-06, with the labels that each got.

#3 Adding Structs, Enums, and Game System Singleton Pattern
  src/CRougeLite.c
  src/CRougeLite.h
  src/clearResources.c
  src/common.h
  src/defs.h
  src/engine/draw.c
  src/engine/draw.h
  src/engine/init.c
  src/engine/init.h
  src/engine/input.c
  src/engine/input.h
  src/init.c
  src/resources/knight.png
  src/structs.h
Labels: enhancement

#4 :construction: Refactor and code cleaning
  src/CRougeLite.c
  src/clearResources.c
  src/common.h
  src/defs.h
  src/engine/init.h
  src/resources/ChikBoy_idle.png
  src/resources/ChikBoy_run.png
  src/resources/Meow-Knight_Idle.png
  src/resources/bullet.png
  src/resources/noBKG_KnightIdle_strip.png
  src/structs.h
  src/system/clearResources.c
  src/system/draw.c
  src/system/draw.h
  src/system/init.c
  src/system/init.h
  src/system/input.c
  src/system/input.h
Labels: bug, enhancement

#13 Refact code structure
  .vscode/settings.json
  src/CRougeLite.c
  src/CRougeLite.h
  src/common.h
  src/defs.h
  src/game/combatAction.c
  src/game/combatAction.h
  src/game/enemy.c
  src/game/enemy.h
  src/game/path.c
  src/game/path.h
  src/game/player.c
  src/game/player.h
  src/game/weapon.c
  src/game/weapon.h
  src/structs.h
  src/system/atlas.c
  src/system/clearResources.c
  src/system/draw.c
  src/system/init.c
  src/system/init.h
  src/system/input.c
Labels: documentation, enhancement

#18 :beetle: DEBUG MENU
  src/CRougeLite.c
  src/common.h
  src/game/debugMenu.c
  src/game/debugMenu.h
  src/libs/raygui.h
  src/structs.h
  src/system/draw.c
  src/system/draw.h
  src/system/init.c
Labels: enhancement

#20 Collision system
  src/CRougeLite.c
  src/defs.h
  src/game/combatAction.c
  src/game/combatAction.h
  src/game/enemy.c
  src/game/player.c
  src/game/weapon.c
  src/structs.h
  src/system/collision.c
  src/system/collision.h
  src/system/draw.c
  src/system/draw.h
  src/system/init.c
  src/system/input.c
  src/system/map.c
Labels: enhancement

#21 Collision system with Hit object
  docs/collision-system.md
  src/game/combatAction.c
  src/game/combatAction.h
  src/game/enemy.c
  src/game/enemy.h
  src/game/player.c
  src/game/player.h
  src/game/weapon.c
  src/structs.h
  src/system/collision.c
  src/system/collision.h
  src/system/init.c
Labels: documentation, enhancement
